# /docker-compose.yml
services:
  monitoring_app:
    # Build the Docker image from the Dockerfile in the current directory
    build: .
    # Name the container for easy identification
    container_name: dispatch_monitoring_service
    # CORRECTED command to run the web.py Streamlit app
    command: streamlit run src/web.py --server.port 8501 --server.address 0.0.0.0
    # Map port 8501 from the container to port 8501 on your local machine
    ports:
      - "8501:8501"
    # Mount the entire project directory into the /app directory in the container
    # This allows the feedback mechanism to save images to your local disk
    # and allows you to change code without rebuilding the image.
    volumes:
      - .:/app