# /config/data.yaml

# IMPORTANT: Update this path to match your project folder in Google Drive
path: /content/drive/MyDrive/Intelligent_Monitor_System

# Paths to train and val image directories, RELATIVE to the 'path' defined above.
train: Dataset/Detection/train/images
val: Dataset/Detection/val/images

# Number of classes
nc: 6

# Class names - The order MUST match your label IDs (0, 1, 2, 3, 4, 5)
names:
  - dish_empty
  - dish_kakigori
  - dish_not_empty
  - tray_empty
  - tray_kakigori
  - tray_not_empty